dnsLess:
  publicUrl: http://localhost:3000/
http:
  port: 3000
  ip: 127.0.0.1
auth:
  adminAccessKey: iuahwd0ba87hw0bd7a8hwd
  trustedApps: "*@https://pryv.github.io*, *@https://*.rec.la*"
eventFiles:
  attachmentsDirPath: var-pryv/attachment-files
service:
  name: Open-Pryv.io
  support: https://pryv.com/open-pryv-non-configured-page/
  terms: https://pryv.com/open-pryv-non-configured-page/
  home: https://pryv.com/open-pryv-non-configured-page/
  eventTypes: https://api.pryv.com/event-types/flat.json
services:
  email:
    enabled:
      welcome: true
      resetPassword: true
custom:
  systemStreams:
    account:
      -
        isIndexed: true
        isUnique: true
        isShown: true
        isEditable: true
        type: email/string
        name: Email
        id: email
        isRequiredInValidation: true