name: Open Pryv.io CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [18.16.0]

    steps:
    - name: Install `just`
      uses: extractions/setup-just@v2

    - name: Checkout repository with submodules
      uses: actions/checkout@v4

    - name: Install Node.js with version ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}


    - name: Setup Open Pryv.io
      run: |
        npm run setup-dev-env
        npm install
        sudo apt-get install graphicsmagick

    - name: Run tests on Open Pryv.io with coverage
      run: |
        IS_CI=true just test-cover-lcov

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: pryv/open-pryv.io