version: "3.8"
services:
  open-pryv.io:
    build: 
      context: ../
      dockerfile: ./docker/Dockerfile.api
    image: pryvio/open-pryv.io:${PRYV_TAG}
    container_name: "open-pryv-api"
    restart: "always"
    ports:
      - ${PRYV_PORT}:3000
    volumes:
      - ${PRYV_BASE}/configs:/app/configs
      - ${PRYV_BASE}/public_html:/app/public_html
      - ${PRYV_BASE}/var-pryv:/app/var-pryv
    depends_on:
      - open-pryv-mongo
    networks:
      - app-network

  open-pryv-mail:
    build: 
      context: ../
      dockerfile: ./docker/Dockerfile.mail
    image: pryvio/open-pryv.io-mail:${PRYV_TAG}
    container_name: "open-pryv-mail"
    restart: "always"
    depends_on:
      - open-pryv.io
    volumes:
      - ${PRYV_BASE}/var-pryv/logs/:/app/var-pryv/maillogs
    networks:
      - app-network

  open-pryv-mongo:
    image: mongo:6.0.5
    container_name: "open-pryv-mongo"
    restart: "always"
    volumes:
      - ${PRYV_BASE}/var-pryv/db:/data/db
      - ${PRYV_BASE}/var-pryv/db-backup:/data/backup/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
