dnsLess:
  publicUrl: "https://my-computer.backloop.dev:3000/"
http:
  port: 3000 # (ignored with docker)
  ip: 127.0.0.1 # (ignored with docker)
  ssl:
    backloop.dev: true
auth:
  adminAccessKey: BACKLOOP-ADMIN-KEY-UNSECURE
  trustedApps: "*@https://pryv.github.io, *@https://*.rec.la*, *@https://*.backloop.dev*"
service:
  serial: 1000001 # change serial number each time assets content needs to be reloaded by clients
  name: Open-Pryv.io
  support: https://pryv.com/open-pryv-non-configured-page/
  terms: https://pryv.com/open-pryv-non-configured-page/
  home: https://pryv.com/open-pryv-non-configured-page/
  eventTypes: https://pryv.github.io/event-types/flat.json
services:
  email:
    enabled:
      welcome: true
      resetPassword: true
custom:
  systemStreams:
    account:
      -
        isIndexed: true
        isUnique: true
        isShown: true
        isEditable: true
        type: email/string
        name: Email
        id: email
        isRequiredInValidation: true