version: "3.8"
services:
    open-pryv-core:
        build: 
          context: ../..
          dockerfile: ./Dockerfile
        image: pryvio/open-pryv-core:${TAG}
        command: "yarn api"
        container_name: "open-pryv-core"
        restart: "always"
        ports:
          - 3000:3000
        volumes:
          - ./dockerized-config-no-ssl.json:/app/config.json
          - ../../public_html/:/app/public_html/
        depends_on:
            - open-pryv-mongo
        networks:
          - app-network

    open-pryv-mail:
        image: pryvio/open-pryv-core:${TAG}
        command: "yarn mail"
        container_name: "open-pryv-mail"
        restart: "always"
        depends_on:
            - open-pryv-core
        volumes:
          - ../../var-pryv/logs/:/app/var-pryv/logs/
          - ./dockerized-service-mail-config.hjson:/app/service-mail/config.hjson
        networks:
          - app-network

    open-pryv-mongo:
        image: mongo:3.6.18
        container_name: "open-pryv-mongo"
        restart: "always"
        volumes:
            - ../../var-pryv/mongodb/conf/:/app/conf/:ro
            - ../../var-pryv/mongodb/data/:/app/data/
            - ../../var-pryv/mongodb/log/:/app/log/
            - ../../var-pryv/mongodb/backup/:/app/backup/
        networks:
          - app-network

networks:
  app-network:
    driver: bridge
