version: "3"
services:
    open-pryv-core:
        image:  pryvio/open-pryv-core:latest
        command: "yarn api"
        container_name: "open-pryv-core"
        restart: "always"
        volumes:
            - ./dockerized-config.json:/app/config.json
        depends_on:
            - open-pryv-mongo
        networks:
          - app-network

    open-pryv-mail:
        image: pryvio/open-pryv-core:latest
        command: "yarn mail"
        container_name: "open-pryv-mail"
        restart: "always"
        volumes:
          - ./var-pryv/logs/:/app/var-pryv/logs/
          - ./dockerized-service-mail-config.hjson:/app/service-mail/config.hjson
        depends_on:
            - open-pryv-core
        networks:
          - app-network

    open-pryv-mongo:
        image: mongo:3.6.18
        container_name: "open-pryv-mongo"
        restart: "always"
        volumes:
          - ./var-pryv/mongodb/conf/:/app/conf/:ro
          - ./var-pryv/mongodb/data/:/app/data/
          - ./var-pryv/mongodb/log/:/app/log/
          - ./var-pryv/mongodb/backup/:/app/backup/
        networks:
          - app-network

    open-pryv-nginx:
        image:  nginx:latest
        container_name: "open-pryv-nginx"
        volumes:
          # You can load custom nginx config and use env variables in it
          - ./nginx-templates:/etc/nginx/templates
          - ./var-pryv/certbot/www:/var/www/certbot
          - ./var-pryv/certbot/conf:/etc/letsencrypt
        ports:
          - 80:80
          - 443:443
        depends_on:
          - open-pryv-core
        networks:
          - app-network
        environment:
         - HOSTNAME=${HOSTNAME}
         - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx

    open-pryv-certbot:
        image: certbot/certbot
        container_name: "open-pryv-certbot"
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
        depends_on:
          - open-pryv-nginx
        volumes:
          - ./var-pryv/certbot/conf:/etc/letsencrypt
          - ./var-pryv/certbot/www:/var/www/certbot
networks:
  app-network:
    driver: bridge    
