name: Pryv-registration-server deployment

on: 
  push:
    tags:
      - '*'
    branches:
      - 'feature/automate-build'
jobs:
  build:

    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node-version: [12.13]

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v2
      with:
        submodules: true
        token: ${{ secrets.SECRET_FOR_READING_SUBMODULES }}
        fetch-depth: 3
        clean: false
        
    - name: Install Node.js with version ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Download pryv.io-open-source
      uses: actions/checkout@v2
      with:
        repository: pryv/pryv.io-open-source
        token: ${{ secrets.SECRET_FOR_READING_SUBMODULES }}
        path: dest
      
    - name: yarn install
      run: yarn install
      
    - name: yarn build and prepend licenses
      run: cd licenser && yarn install && cd .. && yarn build
      
    - name: Run tests on build
      run: echo 'I pretend that I run the tests'
      
    - name: Commit and push to open Pryv 
      run: cd dest && yarn remove test-helpers && git status && git diff && echo 'version'

    - name: Login to the docker hub containers registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_PRYV_SERVER_DOCKERHUB }}
        username: ${{ secrets.REGISTRY_PRYV_USERNAME_DOCKERHUB }}
        password: ${{ secrets.REGISTRY_PRYV_PASSWORD_DOCKERHUB }}

    - name: Build core image
      run: cd dest && TAG=latest docker-compose -f configs/local-docker/docker-compose.no-ssl.yml build open-pryv-core

    - name: Upload new image to docker hub
      run: docker images && docker push pryvio/open-pryv-core:latest

    - name: Upload image with version tag to docker hub
      run: docker tag pryvio/open-pryv-core:latest pryvio/open-pryv-core:${{ env.RELEASE_VERSION }} && docker images && docker push pryvio/open-pryv-core:${{ env.RELEASE_VERSION }}